export const SEARCHFIELD = 'SEARCHFIELD';

export const ARTIST_PENDING = 'ARTIST_PENDING';
export const ARTIST_SUCCESS = 'ARTIST_SUCCESS';
export const ARTIST_FAILURE = 'ARTIST_FAILURE';

export const EVENTS_PENDING = 'EVENTS_PENDING';
export const EVENTS_SUCCESS = 'EVENTS_SUCCESS';
export const EVENTS_FAILURE = 'EVENTS_FAILURE';
